spring:
  datasource:
    url: jdbc:mariadb://192.168.25.55:3306/Daile
    username: daile
    password: dailepass
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  session:
    timeout: 86400
    jdbc:
      initialize-schema: always
daile:
  jwt-key: "rTPmA9Sgk+Q1XwuJbG7E6xFFUhQpdi+al5iyPnRTK/Q="
server:
  servlet:
    session:
      cookie:
        max-age: 172800

